config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  resources :courses
  devise_for :users, :controllers => { :registrations => "registrations" }, :path_prefix => 'd'
  resources :students do
    post :bulk_print, :on => :collection
    get :course_data
  end
  root 'students#index'
  match '/users',   to: 'users#index',   via: 'get'
  resources :users
  resources :student_imports
  resources :themes do
    put :update_theme
  end
end

app/models/student.rb
class Student < ApplicationRecord
     belongs_to :user
     belongs_to :course # course id in school table
     #form field validation
     validates :name, presence: true, length: {maximum: 255}, format: { :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/, message: "may only contain letters and numbers." }
     #validates :code,  presence: true
     scope :course_ordered, ->(order) { includes(:course).order("courses.title" + " " + order) }
 
     #simple search form
     def self.search(search)
         if search.present? 
             where('user_id = ?', search).order(created_at: :desc)
         else
             all.order(created_at: :desc)
         end
     end

     def self.filter(term)
        if term.present?
            where('name LIKE ?', "%#{search}%")
        else
            all
        end
    end
 
     def self.to_csv(options = {})
         CSV.generate(options) do |csv|
           csv << column_names
           all.each do |student|
             csv << student.attributes.values_at(*column_names)
           end
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attr_accessor :login, :skip_validation
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: false }
  validates :name, presence: true, length: {maximum: 255}, uniqueness: { case_sensitive: false }, format: { :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/, message: "may only contain letters and numbers." }
  validates :password, length: { minimum: 8}
  validate :password_complexity, unless: :skip_validation
  validate :validate_name, unless: :skip_validation
  has_many :students
  has_many :courses
  belongs_to :theme

  #overrrite the build method to login with name or email
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(name) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:name) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  def password_complexity
    if password.present?
        if !password.match(/\A[0-9A-Za-z\+\*\.\-\?_!#$%&=\/]+\z/) 
          errors.add :password, "Password complexity requirement not met"
        end
    end
  end

  def validate_name
    if User.where(email: name).exists?
      errors.add(:name, :invalid)
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction
  
  def index
    if current_user.admin?
        if sort_column == "title"
          @resources = Student.search(params[:user_id] ).course_ordered(sort_direction).page(params[:page]).per(params[:per])
        else
          @resources = Student.search(params[:user_id] ).reorder(sort_column + " " + sort_direction).page(params[:page]).per(params[:per])
        end
        respond_to do |format|
          format.html
          format.csv { send_data @resources.to_csv }
          format.xls  #{ send_data @products.to_csv(col_sep: "\t") }
        end
    else
      @resources = Student.search(params[:search]).reorder(sort_column + " " + sort_direction).where(user_id: current_user.id).page(params[:page]).per(params[:per])
      render :user_index
    end
  end
  
  def course_data
    if params[:user_id] == '1' 
      @select_course = Course.all
    else
      @select_course = Course.where(user_id: params[:user_id])
    end
    respond_to do |format|
      format.json { render json: @select_course }
    end
  end

  def bulk_print
    @pdf_resources = Student.where(id: params[:student_ids])
    @pdf_resources.each do |pdf| 
      pdf.update(status: 'complete')
      pdf.save!
    end
    pdf = StudentPdf.new(@pdf_resources)
    send_data pdf.render,
              filename: "student_#{Time.now}",
              type: 'application/pdf',
              disposition: 'inline'
  end

  def show
    @student = Student.find(params[:id])
    if current_user.admin?
      @student.update(status: 'complete')
      @student.save!
    end
    respond_to do |format|
      format.html
      format.json { head :no_content }
      format.pdf do
        pdf = StudentPdf.new([@student])
        send_data pdf.render,
                  filename: "student_#{@student.name}",
                  type: 'application/pdf',
                  disposition: 'inline'
      end
    end
  end

  def new
    @student = current_user.students.build(status: 'imcomplete')
  end

  def edit
  end

  def create
    if current_user.admin?
      @student = Student.new(student_params)
    else
      @student = current_user.students.build(student_params)
    end
    @student.status = 'imcomplete'
    respond_to do |format|
      if @student.save
        format.html { redirect_to students_url, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to students_url, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_student
      @student = Student.find(params[:id])
    end

    def student_params
      params.require(:student).permit(:code, :name, :course_id, :user_id, :student_ids)
    end

    def sort_column
      params[:sort].present? ? params[:sort] : "created_at"
    end
      
    def sort_direction
      params[:direction].present? ? params[:direction] : "desc"
    end
end

app/helpers/students_helper.rb
module StudentsHelper
    include ApplicationHelper
    def sort_column
        params[:sort].present? ? params[:sort] : "created_at"
    end
      
    def sort_direction
        params[:direction].present? ? params[:direction] : "asc"
    end
end

app/views/students/_form.html.erb
<div class="row">
  <div class="col-md-6 col-xs-6 col-md-offset-3">
    <%= form_with(model: student, local: true) do |form| %>
      <% if student.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(student.errors.count, "error") %> error for  this student from being saved:</h2>

          <ul>
          <% student.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :code %>
        <%= form.text_field :code, id: :student_code %>
      </div>

      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name, id: :student_name %>
      </div>

      <div class="field">
          <%= form.label :course %>
          <div class="row">
            <% if current_user.admin? %>
            <div class="col-md-6">
              <%= form.select :user_id, User.all.map{ |c| [c.name, c.id]}, {:prompt => "select"} , :id => "user_id" %>
            </div>
            <div class="col-md-6">
            <% else %>
            <div class="col-md-12">
            <% end %>
            <% if current_user.admin? %>
              <% @course =student.course_id.present? ? Course.where(id: student.course_id ): Course.all %>
              <%= form.select :course_id, @course.map{ |c| [c.title, c.id]}, {:prompt => "select"} , :id => "course_id" %>
            <% else %>
              <%= form.select :course_id, options_from_collection_for_select(current_user.courses.all, 'id', 'title'), id: "course_id" %>
            <% end %>
            </div>
          </div>
      </div>

      <div class="actions center">
        <%= form.submit "submit", class: "btn btn-default btn btn-float btn-info" %>
        <%= link_to 'cancel', students_path, class: " btn btn-default btn-float btn-cancel button4" %>
      </div>
    <% end %>
  </div>
</div>
<script>
$( document ).ready(function() {
    if (window.location.href.indexOf("edit") != -1 ){
      var current_url = 'course_data'
    }else{
      var current_url = 'student/course_data'
    }
   $("#user_id").on("change",function(){
      $.ajax({
        type: 'GET',
        url: current_url,
        data: { user_id: $("#user_id").val()},
        dataType: "json",
        success: function(data){
          $('#course_id > *').remove();
          $('#course_id').append('<option value="">select</option>');
          $.each(data,function(index, item){
          $('#course_id').append('<option value="'+ item.id + '">'+ item.title +'</option>');
          });
        }
      })
   });
});
</script>

app/views/students/_index_footer.html.erb
<div class="fixed-table-pagination">
  <div class="pull-left pagination-detail">
    <span class="pagination-info">
      <%= page_entries_info  @students %>
    </span>
    <% if  @students.count > 24 %>
      <span class="page-list">
          <%= form_tag root_path, method: :get, id: 'per_form' do %>
              <%= t ("views.pagination.max_per_page") %>
              <%= select_tag :per, options_for_select([25,50,100], selected: params[:per] || 25) %>
              <%= t ("views.pagination.pages") %>
            <% end %>
      </span>
    <% end %>
  </div>
  <!-- add limit on page number -->
  <%if  @students.current_page < 3%>
    <% @window = 5 -  @students.current_page%>
  <%elsif  @students.last_page?%>
    <% @window =  4  %>
  <%elsif  @students.current_page ==  @students.total_pages - 1 %>
    <% @window =  3  %>
  <% else %>
    <% @window =  2 %>
  <% end %>

    <div class="pull-right paginate-container">
          <%= paginate  @students, window: @window%>
    </div>
</div>

<script type="text/javascript" >
  $(function(){
    $('#per').change(
      function() {
       $('#per_form').submit();
      });
  });
</script>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

app/views/students/index.html.erb
<h1>All Students</h1>
<%= link_to 'New Student', new_student_path, class: "btn btn-info btn-float tooltips" %>
<span>
<%= link_to "Import", new_student_import_path, class: "btn btn-info btn-float tooltips" %>
<%= link_to "Export", students_path(format: "csv"), class: "btn btn-info btn-float tooltips"  %>
</span>
<table id="student" class="table table-hover">
  <thead>
    <tr>
      <th>&nbsp; &nbsp; &nbsp;</th>
      <th><%= sortable "code", "Student Code" %></th>
      <th><%= sortable "name", "Student Name" %></th>
      <th><%= sortable "title", "Course" %></th>
      <th><%= sortable "created_at", "Created Time" %></th>
      <th><%= sortable "updated_at", "Updated Time" %></th>
      
      <th style="width: 150px;">
        <%= form_tag students_path, :method => 'get', :id => "user_select" do %>
          <%= select_tag :user_id, options_from_collection_for_select(User.all, 'id', 'name'), id: "user_select", onchange: 'this.form.submit();', prompt: " " %>
        <% end %>
      </th>
      <th><%= sortable "status", "Status" %></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      
    </tr>
  </thead>

  <tbody>
  <%= form_tag bulk_print_students_path, id: "print_all" do %>
    <% @resources.each do |student| %>
      <tr>
        <td class="custom-control custom-checkbox"><%= check_box_tag 'student_ids[]', student.id, false %></td>
        <td><%= student.code %></td>
        <td><%= student.name %></td>
        <td><%= student.course.title %></td>
        <td> <%= student.created_at.strftime("%Y-%m-%d %I:%M") %></td>
        <td><%= student.updated_at.strftime("%Y-%m-%d %I:%M")%> </td>
        <td><%= student.user.name %></td>
        <td><%= student.status%> </td>
        <td><%= link_to student_path(student, format: 'pdf'), class: "btn btn-default btn btn-info" do %>
          <i class="far fa-file-pdf"></i>
       <% end %>
       </td>
       <td><%= link_to edit_student_path(student), class: "btn btn-default btn btn-success" do %>
         <i class="glyphicon glyphicon-edit"></i>
       <% end %>
       </td>
       <td><%= link_to student, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn btn-danger" do %>
         <i class="glyphicon glyphicon-trash"></i>
       <% end %>
       </td>
      </tr>
    <% end %>
    <%= submit_tag "Print to PDF", class: "btn btn-success pdf_print" %>
    <% end %>
  </tbody>
</table>
<%= render 'index_footer' %>

app/views/students/new.html.erb
<h1>New Student</h1>

 <%= render 'form', student: @student %>
 

app/views/students/show.html.erb
<h1>Student Information</h1>
<div class="row">
  <div class="col-md-6 col-xs-6 col-md-offset-3">
    <p id="notice"><%= notice %></p>

    <dl class="dl-horizontal">
      <dt>Student Code:</dt>
      <dd><%= @student.code %></dd>
    </dl>

    <dl class="dl-horizontal">
      <dt>Student Name:</dt>
      <dd><%= @student.name %></dd>
    </dl>

    <dl class="dl-horizontal">
      <dt>Email:</dt>
      <dd><%= @student.user.email %></dd>
    </dl>

    <dl class="dl-horizontal">
      <dt>Course:</dt>
      <dd><%= @student.course.name %></dd>
    </dl>

    <%= link_to 'Back', students_path, class: "btn btn-default btn-float btn-cancel"  %>
    <% if current_user.admin? %>
       <%= link_to "Print(PDF)", student_path(@student, format: 'pdf'), class: "btn btn-default btn-float btn-cancel"  %>
    <% end %>
  </div>
</div>

app/views/students/user_index.html.erb
<h1>All Students</h1>
<%= link_to 'New Student', new_student_path, class: "btn btn-primary" %>
<table id="student" class="table table-hover">
  <thead>
    <tr>
    <th><%= sortable "code", "Student Code" %></th>
    <th><%= sortable "name", "Student Name" %></th>
    <th><%= sortable "course", "Course" %>Course</th>
    <th><%= sortable "created_at", "Created Time" %></th>
    <th><%= sortable "updated_at", "Updated Time" %></th>
    <th><%= sortable "status", "Status" %></th>
    <th></th>
    <th></th>
    <th></th>
      
    </tr>
  </thead>

  <tbody>
    
    <% @resources.each do |student| %>
      <tr>
        <td><%= student.code %></td>
        <td><%= student.name %></td>
        <td><%= student.course.name %></td>
        <td> <%= student.created_at %></td>
        <td><%= student.updated_at%> </td>
        <td><%= student.status%> </td>
        <td>
          <%= link_to student, :class => "btn btn-crud-action btn-xs tooltips" do %>
            <i class="glyphicon glyphicon-list-alt"></i>
          <% end %>
        </td>
        <td><%= link_to edit_student_path(student), class: "btn btn-default btn btn-success" do %>
          <i class="glyphicon glyphicon-edit"></i>
        <% end %>
        </td>
        <td><%= link_to student, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn btn-danger" do %>
          <i class="glyphicon glyphicon-trash"></i>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>