config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  resources :courses
  devise_for :users, :controllers => { :registrations => "registrations" }, :path_prefix => 'd'
  resources :students do
    post :bulk_print, :on => :collection
    get :course_data
  end
  root 'students#index'
  match '/users',   to: 'users#index',   via: 'get'
  resources :users
  resources :student_imports
  resources :themes do
    put :update_theme
  end
end

app/models/theme.rb
class Theme < ApplicationRecord
    has_many :users
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: [:show, :edit, :update, :destroy]

  # GET /themes
  # GET /themes.json
  def model 
    @model = Theme
  end
  def index
    @themes = model.all
  end

  # GET /themes/1
  # GET /themes/1.json
  def show
  end

  # GET /themes/new
  def new
    @theme = model.new
  end

  # GET /themes/1/edit
  def edit
  end

  # POST /themes
  # POST /themes.json
  def create
    @theme = model.new(theme_params)

    respond_to do |format|
      if @theme.save
        format.html { redirect_to themes_url, notice: 'Theme was successfully created.' }
        format.json { render :index, status: :created, location: themes_url }
      else
        format.html { render :new }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /themes/1
  # PATCH/PUT /themes/1.json
  def update
    current_user.theme = model.find(params[:id])
    respond_to do |format|
      if @theme.update(theme_params)
        format.html { redirect_to themes_url, notice: 'Theme was successfully updated.' }
        format.json { render :index, status: :ok, location: @themes }
      else
        format.html { render :edit }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_theme
    current_user.skip_validation = true
    current_user.theme_id = params[:theme_id]
    current_user.save(validate: false)
    @current_color = model.where(id: current_user.theme_id).pluck(:color_code)[0]
    @current_color = Theme.where(id: params[:theme_id]).pluck(:color_code)[0]
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @themes, color: @current_color,  notice: 'Theme was successfully updated.' }
    end
  end

  # DELETE /themes/1
  # DELETE /themes/1.json
  def destroy
    @theme.destroy
    respond_to do |format|
      format.html { redirect_to themes_url, notice: 'Theme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theme
      @theme = model.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def theme_params
      params.require(:theme).permit(:name, :color_code, :theme_id)
    end
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/themes/_form.html.erb
<div class="row">
  <div class="col-md-6 col-xs-6 col-md-offset-3">
    <%= form_with(model: theme, local: true) do |form| %>
      <% if theme.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(theme.errors.count, "error") %> prohibited this theme from being saved:</h2>

          <ul>
          <% theme.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name, id: :theme_name %>
      </div>

      <div class="form-group">
        <%= form.label :color_code %>
        <%= form.color_field :color_code, id: :theme_color_code, :class => "form-control" %>
      </div>

        <div class="actions center">
          <%= form.submit "submit", class: "btn btn-default btn btn-float btn-info" %>
          <%= link_to 'cancel', themes_path, class: " btn btn-default btn-float btn-cancel button4" %>
        </div>
    <% end %>
  </div>
</div>

app/views/themes/edit.html.erb
<h1>Editing Theme</h1>

<%= render 'form', theme: @theme %>

app/views/themes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Theme List</h1>
<% if current_user.admin? %>
<%= link_to 'New Theme', new_theme_path, class: "btn btn-info btn-float tooltips" %>
<button onClick="showTable()" class="btn btn-info btn-float tooltips">Show Color List</button>
<% end %>
<table id="theme" class="table table-hover" style="display: none">
  <thead>
    <tr>
      <th> Name</th>
      <th>Color</th>
      <th>Created Time</th>
      <th>Updated Time</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      
    </tr>
  </thead>

  <tbody>
    
    <% @themes.each do |theme| %>
      <tr>
        <td><%= theme.name %></td>
        <td style="background-color: <%= theme.color_code %>"></td>
        <td> <%= theme.created_at.strftime("%Y-%m-%d %I:%M") %></td>
        <td><%= theme.updated_at.strftime("%Y-%m-%d %I:%M")%> </td>
        <td><%= link_to edit_theme_path(theme), class: "btn btn-default btn btn-success" do %>
          <i class="glyphicon glyphicon-edit"></i>
        <% end %>
        <td>
        <% if User.where(theme_id: theme.id).present? %>
          <%= link_to theme, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn btn-danger disabled" do %>
            <i class="glyphicon glyphicon-trash"></i>
          <% end %>
        <% else %>
          <%= link_to theme, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn btn-danger" do %>
            <i class="glyphicon glyphicon-trash"></i>
          <% end %>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="row">
  <% @themes.each do |resource| %>
    
    <div id="resource-<%= resource.id %>" class="theme-panel-container -xs-6 col-xs-6 col-sm-4 col-md-3 col-lg-3">
      <div class="theme-panel <%= resource.id == current_user.theme_id ? 'ti-check checked' : '' %>">
        <div class="theme-img" style="background-color:<%= resource.color_code %>;">
          <%= image_tag "theme_img_no_text.png" %>
        </div>
        <div class="text text-center">
          <%= resource.name %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<script>
  function showTable() {
  var x = document.getElementById("theme");
  if (x.style.display === "none") {
    x.style.display = "table";
  } else {
    x.style.display = "none";
  }
}
  $(function() {
    var $panels = $('.theme-panel'),
        hundleClick = function(event) {
          var that = this;
          var theme_id =  $(that).parent().attr('id').replace('resource-', '');
          $.ajax({
            url: "themes/" + theme_id + "/update_theme",
            type: 'PUT',
            dataType: 'json',
            data: {theme: {id: $(that).parent().attr('id').replace('resource-', '')}},
            success: function(data) {
              $panels.removeClass('ti-check');
              $panels.removeClass('checked');
              $(that).addClass('ti-check');
              $(that).addClass('checked');
              location.reload(); 
            },
            error:function() {
              alert('failed');
            }
          });
        };

    $panels.click(hundleClick);
  });
</script>

app/views/themes/new.html.erb
<h1>New Theme</h1>

<%= render 'form', theme: @theme %>

app/views/themes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @theme.name %>
</p>

<p>
  <strong>Color code:</strong>
  <%= @theme.color_code %>
</p>

<%= link_to 'Back', themes_path %>