config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  resources :courses
  devise_for :users, :controllers => { :registrations => "registrations" }, :path_prefix => 'd'
  resources :students do
    post :bulk_print, :on => :collection
    get :course_data
  end
  root 'students#index'
  match '/users',   to: 'users#index',   via: 'get'
  resources :users
  resources :student_imports
  resources :themes do
    put :update_theme
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!, :authorize_admin
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  # GET /courses
  # GET /courses.json
  def index
    if sort_column == "b_name"
      @resources =  Course.all.branch_ordered(sort_direction).page(params[:page]).per(params[:per])
    else
      @resources = Course.all.reorder(sort_column + " " + sort_direction).page(params[:page]).per(params[:per])
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :description, :user_id, :title)
    end

    def sort_column
      params[:sort].present? ? params[:sort] : "created_at"
    end
      
    def sort_direction
      params[:direction].present? ? params[:direction] : "desc"
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
    include ApplicationHelper
    def sort_column
        params[:sort].present? ? params[:sort] : "created_at"
    end
      
    def sort_direction
        params[:direction].present? ? params[:direction] : "asc"
    end
end

app/views/courses/_form.html.erb
<div class="row">
  <div class="col-md-6 col-xs-6 col-md-offset-3">
    <%= form_with(model: course, local: true) do |form| %>
      <% if course.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

          <ul>
          <% course.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name, id: :course_name %>
      </div>

       <div class="field">
        <%= form.label :title %>
        <%= form.text_field :title, id: :course_title %>
      </div>

      <div class="field">
        <%= form.label :description %>
        <%= form.text_area :description, :cols => 30, :rows => 10 %>
      </div>

      <div class="field">
        <%= form.label :name %>
        <%= form.select :user_id, User.all.map{ |u| [u.name, u.id]}, {:prompt => "select"} %>
      </div>

      <div class="actions center">
        <%= form.submit "submit", class: "btn btn-default btn btn-float btn-info" %>
        <%= link_to 'cancel', courses_path, class: " btn btn-default btn-float btn-cancel button4" %>
      </div>
    <% end %>
  </div>
</div>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses List</h1>
<%= link_to 'New Course', new_course_path, class: "btn btn-info btn-float tooltips"  %>
<table class="table table-hover" id="courses">
  <thead>
    <tr>
      <th><%= sortable "id", "ID" %></th>
      <th><%= sortable "name", "Name" %></th>
      <th><%= sortable "title", "Course Title" %></th>
      <th><%= sortable "description", "Description" %></th>
      <th><%= sortable "b_name", "Branch Name" %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |course| %>
      <tr>
        <td><%= course.id %></td>
        <td><%= course.name %></td>
        <td><%= course.title %></td>
        <td><%= course.description %></td>
        <td><%= course.user.name %></td>
        <td>
          <%= link_to course, :class => "btn btn-crud-action btn-xs tooltips" do %>
            <i class="glyphicon glyphicon-list-alt"></i>
          <% end %>
        </td>
        <td>
          <%= link_to edit_course_path(course), class: "btn btn-default btn btn-success" do %>
            <i class="glyphicon glyphicon-edit"></i>
          <% end %>
        </td>
        <td>
          <%= link_to course, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn btn-danger" do %>
            <i class="glyphicon glyphicon-trash"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render 'layouts/index_footer' %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

app/views/courses/show.html.erb
<h1>Course Information</h1>
<div class="row">
  <div class="col-md-6 col-xs-6 col-md-offset-3">
		<p id="notice"><%= notice %></p>

		<dl class="dl-horizontal">
		  <dt>Name:</dt>
		  <dd><%= @course.name %></dd>
		</dl>

		<dl class="dl-horizontal">
		  <dt>Title:</dt>
		  <dd><%= @course.title %></dd>
		</dl>

		<dl class="dl-horizontal">
		  <dt>Description:</dt>
		  <dd><%= @course.description %></dd>
		</dl>

		<div class="center">
		  <%= link_to 'back', courses_path, class: "position-relative btn btn-default btn-float btn-cancel" %>
		</div>
	</div>
</div>