config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  resources :courses
  devise_for :users, :controllers => { :registrations => "registrations" }, :path_prefix => 'd'
  resources :students do
    post :bulk_print, :on => :collection
    get :course_data
  end
  root 'students#index'
  match '/users',   to: 'users#index',   via: 'get'
  resources :users
  resources :student_imports
  resources :themes do
    put :update_theme
  end
end

app/views/layouts/_footer.html.erb
<% if current_user %>
  <footer class="footer-copyright text-center py-3">
    <div class="text-center">
    <a href="http://www.softguide.herokuapp.com/">Created By Sgswteam</a>
    </div>
  </footer>
<% end %> 

app/views/layouts/_header.html.erb
<% if current_user %>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>                        
        </button>
        <%= link_to "Attendence", root_path, id: "logo",  class: "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          
        <li><%= link_to 'Students', students_path %></li>
        <li><%= link_to 'Courses', courses_path %></li>
        <li><%= link_to 'Users', users_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#"> <%= current_user.name %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit", edit_user_registration_path %></li>
              <li class="divider"></li>
                <li>
                  <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
                </li>
            </ul>
          </li>
          <% else %>
          <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
<% end %>

app/views/layouts/_header1.html.erb
<% if current_user %>
<% @color = current_user.theme_id ? Theme.where(id: current_user.theme_id).pluck(:color_code)[0] : '#204d74'%>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation" style="background-color:<%= @color%>;">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <a class="navbar-brand" style="background-color:<%= @color%>;" href="/students">
      <img src="/assets/test1.png" alt="LOGO">
    </a>
    <ul class="nav navbar-right top-nav">
      <li><a href="#" data-placement="bottom" data-toggle="tooltip" href="#" data-original-title="Stats">
        <i class="fas fa-bars"></i></a>
      </li>            
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-fw fa-user"></i><%= current_user.name if current_user %> <b class="fa fa-angle-down"></b></a>
        <ul class="dropdown-menu">
          <li>
            <%= link_to '<i class="fa fa-fw fa-user"></i>Edit Profile'.html_safe, edit_user_registration_path %>
          </li>
          <li class="divider"></li>
          <li>
            <%= link_to '<i class="fa fa-fw fa-power-off"></i>Logout'.html_safe, destroy_user_session_path, :method => :delete %>
          </li>
        </ul>
      </li>
    </ul>

  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav side-nav" style="background-color:<%= @color%>;">
      <li class="user-mode"> <%= "Admin" if current_user.admin? %></li>
      <li><%= link_to '<i class="fa fa-user"></i>Students'.html_safe, students_path %></li>
      <% if current_user.admin? %>
      <li><%= link_to '<i class="far fa-file"></i>Courses'.html_safe, courses_path %></li>
      <li><%= link_to '<i class="fa fa-fw fa-user"></i>Users'.html_safe, users_path %></li>
      <% end %>
      <li><%= link_to '<i class="fa fa-indent"></i>Themes'.html_safe, themes_path %></li>
    </ul>
  </div>
</nav>
<% end %>

<script>
$("document").ready(function(){
   $(function(){
        $('a').each(function(){
            if ($(this).prop('href') == window.location.href) {
                $(this).addClass('active'); $(this).parents('li').addClass('active');
            }
        });
    });
});
</script>

app/views/layouts/_index_footer.html.erb
<div class="fixed-table-pagination">
  <div class="pull-left pagination-detail">
    <span class="pagination-info">
      <%= page_entries_info  @resources %>
    </span>
    <% if  @resources.count > 24 %>
      <span class="page-list">
          <%= form_tag root_path, method: :get, id: 'per_form' do %>
              <%= t ("views.pagination.max_per_page") %>
              <%= select_tag :per, options_for_select([25,50,100], selected: params[:per] || 25) %>
              <%= t ("views.pagination.pages") %>
            <% end %>
      </span>
    <% end %>
  </div>
  <!-- add limit on page number -->
  <%if  @resources.current_page < 3%>
    <% @window = 5 -  @resources.current_page%>
  <%elsif  @resources.last_page?%>
    <% @window =  4  %>
  <%elsif  @resources.current_page ==  @resources.total_pages - 1 %>
    <% @window =  3  %>
  <% else %>
    <% @window =  2 %>
  <% end %>

    <div class="pull-right paginate-container">
          <%= paginate  @resources, window: @window%>
    </div>
</div>

<script type="text/javascript" >
  $(function(){
    $('#per').change(
      function() {
       $('#per_form').submit();
      });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Attendence</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header1' %>
    <div id="wrapper">
     
      <div id="page-wrapper">
        <div class="container-fluid">
            <div class="row" id="main" >
            <!-- 
              <% flash.each do |message_type, message| %> 
                <div class="alert alert-<%= message_type %>"><%= message %></div>
              <% end %>
            -->
              <div class="col-sm-12 col-md-12 well" id="content">
                  <%= yield %>
              </div>
            </div>
          </div>
      </div>
    </div>
  </body>
</html>